export interface EmojiItem {
  name: string;
  file: string;
}

export const EMOJI_LIST: EmojiItem[] = [
  { name: '生气a', file: 'emoji_angry_a.png' },
  { name: '生气b', file: 'emoji_angry_b.png' },
  { name: '生气c', file: 'emoji_angry_c.png' },
  { name: '生气d', file: 'emoji_angry_d.png' },
  { name: '尴尬a', file: 'emoji_awkward_a.png' },
  { name: '尴尬b', file: 'emoji_awkward_b.png' },
  { name: '尴尬c', file: 'emoji_awkward_c.png' },
  { name: '尴尬d', file: 'emoji_awkward_d.png' },
  { name: '再见a', file: 'emoji_bye_a.png' },
  { name: '再见b', file: 'emoji_bye_b.png' },
  { name: '再见c', file: 'emoji_bye_c.png' },
  { name: '再见d', file: 'emoji_bye_d.png' },
  { name: '加油a', file: 'emoji_cheerup_a.png' },
  { name: '加油b', file: 'emoji_cheerup_b.png' },
  { name: '加油c', file: 'emoji_cheerup_c.png' },
  { name: '加油d', file: 'emoji_cheerup_d.png' },
  { name: '安慰a', file: 'emoji_comfort_a.png' },
  { name: '安慰b', file: 'emoji_comfort_b.png' },
  { name: '安慰c', file: 'emoji_comfort_c.png' },
  { name: '安慰d', file: 'emoji_comfort_d.png' },
  { name: '暴躁a', file: 'emoji_cranky_a.png' },
  { name: '暴躁b', file: 'emoji_cranky_b.png' },
  { name: '暴躁c', file: 'emoji_cranky_c.png' },
  { name: '暴躁d', file: 'emoji_cranky_d.png' },
  { name: '哭泣a', file: 'emoji_cry_a.png' },
  { name: '哭泣b', file: 'emoji_cry_b.png' },
  { name: '哭泣c', file: 'emoji_cry_c.png' },
  { name: '哭泣d', file: 'emoji_cry_d.png' },
  { name: '走神a', file: 'emoji_distract_a.png' },
  { name: '走神b', file: 'emoji_distract_b.png' },
  { name: '走神c', file: 'emoji_distract_c.png' },
  { name: '走神d', file: 'emoji_distract_d.png' },
  { name: '送花a', file: 'emoji_flower_a.png' },
  { name: '送花b', file: 'emoji_flower_b.png' },
  { name: '送花c', file: 'emoji_flower_c.png' },
  { name: '送花d', file: 'emoji_flower_d.png' },
  { name: '厉害a', file: 'emoji_great_a.png' },
  { name: '厉害b', file: 'emoji_great_b.png' },
  { name: '厉害c', file: 'emoji_great_c.png' },
  { name: '厉害d', file: 'emoji_great_d.png' },
  { name: '爱心a', file: 'emoji_heart_a.png' },
  { name: '爱心b', file: 'emoji_heart_b.png' },
  { name: '爱心c', file: 'emoji_heart_c.png' },
  { name: '爱心d', file: 'emoji_heart_d.png' },
  { name: '开心a', file: 'emoji_joy_a.png' },
  { name: '开心b', file: 'emoji_joy_b.png' },
  { name: '开心c', file: 'emoji_joy_c.png' },
  { name: '开心d', file: 'emoji_joy_d.png' },
  { name: '不要', file: 'emoji_nope.png' },
  { name: '纸条', file: 'emoji_paper.png' },
  { name: '得意a', file: 'emoji_pride_a.png' },
  { name: '得意b', file: 'emoji_pride_b.png' },
  { name: '得意c', file: 'emoji_pride_c.png' },
  { name: '得意d', file: 'emoji_pride_d.png' },
  { name: '揍你a', file: 'emoji_punch_a.png' },
  { name: '揍你b', file: 'emoji_punch_b.png' },
  { name: '揍你c', file: 'emoji_punch_c.png' },
  { name: '揍你d', file: 'emoji_punch_d.png' },
  { name: '疑问a', file: 'emoji_question_a.png' },
  { name: '疑问b', file: 'emoji_question_b.png' },
  { name: '疑问c', file: 'emoji_question_c.png' },
  { name: '疑问d', file: 'emoji_question_d.png' },
  { name: '石头', file: 'emoji_rock.png' },
  { name: '玫瑰', file: 'emoji_rose.png' },
  { name: '难过a', file: 'emoji_sad_a.png' },
  { name: '难过b', file: 'emoji_sad_b.png' },
  { name: '难过c', file: 'emoji_sad_c.png' },
  { name: '难过d', file: 'emoji_sad_d.png' },
  { name: '剪刀', file: 'emoji_scissors.png' },
  { name: '叹气a', file: 'emoji_sigh_a.png' },
  { name: '叹气b', file: 'emoji_sigh_b.png' },
  { name: '叹气c', file: 'emoji_sigh_c.png' },
  { name: '叹气d', file: 'emoji_sigh_d.png' },
  { name: '唱歌a', file: 'emoji_sing_a.png' },
  { name: '唱歌b', file: 'emoji_sing_b.png' },
  { name: '唱歌c', file: 'emoji_sing_c.png' },
  { name: '唱歌d', file: 'emoji_sing_d.png' },
  { name: '偷笑a', file: 'emoji_sneaky_a.png' },
  { name: '偷笑b', file: 'emoji_sneaky_b.png' },
  { name: '偷笑c', file: 'emoji_sneaky_c.png' },
  { name: '偷笑d', file: 'emoji_sneaky_d.png' },
  { name: '惊讶a', file: 'emoji_surprise_a.png' },
  { name: '惊讶b', file: 'emoji_surprise_b.png' },
  { name: '惊讶c', file: 'emoji_surprise_c.png' },
  { name: '惊讶d', file: 'emoji_surprise_d.png' },
  { name: '害羞a', file: 'emoji_tete_a.png' },
  { name: '害羞b', file: 'emoji_tete_b.png' },
  { name: '害羞c', file: 'emoji_tete_c.png' },
  { name: '害羞d', file: 'emoji_tete_d.png' },
];

// Static require map for emoji images
const emojiMap: Record<string, any> = {
  'emoji_angry_a.png': require('../../assets/emojis/emoji_angry_a.png'),
  'emoji_angry_b.png': require('../../assets/emojis/emoji_angry_b.png'),
  'emoji_angry_c.png': require('../../assets/emojis/emoji_angry_c.png'),
  'emoji_angry_d.png': require('../../assets/emojis/emoji_angry_d.png'),
  'emoji_awkward_a.png': require('../../assets/emojis/emoji_awkward_a.png'),
  'emoji_awkward_b.png': require('../../assets/emojis/emoji_awkward_b.png'),
  'emoji_awkward_c.png': require('../../assets/emojis/emoji_awkward_c.png'),
  'emoji_awkward_d.png': require('../../assets/emojis/emoji_awkward_d.png'),
  'emoji_bye_a.png': require('../../assets/emojis/emoji_bye_a.png'),
  'emoji_bye_b.png': require('../../assets/emojis/emoji_bye_b.png'),
  'emoji_bye_c.png': require('../../assets/emojis/emoji_bye_c.png'),
  'emoji_bye_d.png': require('../../assets/emojis/emoji_bye_d.png'),
  'emoji_cheerup_a.png': require('../../assets/emojis/emoji_cheerup_a.png'),
  'emoji_cheerup_b.png': require('../../assets/emojis/emoji_cheerup_b.png'),
  'emoji_cheerup_c.png': require('../../assets/emojis/emoji_cheerup_c.png'),
  'emoji_cheerup_d.png': require('../../assets/emojis/emoji_cheerup_d.png'),
  'emoji_comfort_a.png': require('../../assets/emojis/emoji_comfort_a.png'),
  'emoji_comfort_b.png': require('../../assets/emojis/emoji_comfort_b.png'),
  'emoji_comfort_c.png': require('../../assets/emojis/emoji_comfort_c.png'),
  'emoji_comfort_d.png': require('../../assets/emojis/emoji_comfort_d.png'),
  'emoji_cranky_a.png': require('../../assets/emojis/emoji_cranky_a.png'),
  'emoji_cranky_b.png': require('../../assets/emojis/emoji_cranky_b.png'),
  'emoji_cranky_c.png': require('../../assets/emojis/emoji_cranky_c.png'),
  'emoji_cranky_d.png': require('../../assets/emojis/emoji_cranky_d.png'),
  'emoji_cry_a.png': require('../../assets/emojis/emoji_cry_a.png'),
  'emoji_cry_b.png': require('../../assets/emojis/emoji_cry_b.png'),
  'emoji_cry_c.png': require('../../assets/emojis/emoji_cry_c.png'),
  'emoji_cry_d.png': require('../../assets/emojis/emoji_cry_d.png'),
  'emoji_distract_a.png': require('../../assets/emojis/emoji_distract_a.png'),
  'emoji_distract_b.png': require('../../assets/emojis/emoji_distract_b.png'),
  'emoji_distract_c.png': require('../../assets/emojis/emoji_distract_c.png'),
  'emoji_distract_d.png': require('../../assets/emojis/emoji_distract_d.png'),
  'emoji_flower_a.png': require('../../assets/emojis/emoji_flower_a.png'),
  'emoji_flower_b.png': require('../../assets/emojis/emoji_flower_b.png'),
  'emoji_flower_c.png': require('../../assets/emojis/emoji_flower_c.png'),
  'emoji_flower_d.png': require('../../assets/emojis/emoji_flower_d.png'),
  'emoji_great_a.png': require('../../assets/emojis/emoji_great_a.png'),
  'emoji_great_b.png': require('../../assets/emojis/emoji_great_b.png'),
  'emoji_great_c.png': require('../../assets/emojis/emoji_great_c.png'),
  'emoji_great_d.png': require('../../assets/emojis/emoji_great_d.png'),
  'emoji_heart_a.png': require('../../assets/emojis/emoji_heart_a.png'),
  'emoji_heart_b.png': require('../../assets/emojis/emoji_heart_b.png'),
  'emoji_heart_c.png': require('../../assets/emojis/emoji_heart_c.png'),
  'emoji_heart_d.png': require('../../assets/emojis/emoji_heart_d.png'),
  'emoji_joy_a.png': require('../../assets/emojis/emoji_joy_a.png'),
  'emoji_joy_b.png': require('../../assets/emojis/emoji_joy_b.png'),
  'emoji_joy_c.png': require('../../assets/emojis/emoji_joy_c.png'),
  'emoji_joy_d.png': require('../../assets/emojis/emoji_joy_d.png'),
  'emoji_nope.png': require('../../assets/emojis/emoji_nope.png'),
  'emoji_paper.png': require('../../assets/emojis/emoji_paper.png'),
  'emoji_pride_a.png': require('../../assets/emojis/emoji_pride_a.png'),
  'emoji_pride_b.png': require('../../assets/emojis/emoji_pride_b.png'),
  'emoji_pride_c.png': require('../../assets/emojis/emoji_pride_c.png'),
  'emoji_pride_d.png': require('../../assets/emojis/emoji_pride_d.png'),
  'emoji_punch_a.png': require('../../assets/emojis/emoji_punch_a.png'),
  'emoji_punch_b.png': require('../../assets/emojis/emoji_punch_b.png'),
  'emoji_punch_c.png': require('../../assets/emojis/emoji_punch_c.png'),
  'emoji_punch_d.png': require('../../assets/emojis/emoji_punch_d.png'),
  'emoji_question_a.png': require('../../assets/emojis/emoji_question_a.png'),
  'emoji_question_b.png': require('../../assets/emojis/emoji_question_b.png'),
  'emoji_question_c.png': require('../../assets/emojis/emoji_question_c.png'),
  'emoji_question_d.png': require('../../assets/emojis/emoji_question_d.png'),
  'emoji_rock.png': require('../../assets/emojis/emoji_rock.png'),
  'emoji_rose.png': require('../../assets/emojis/emoji_rose.png'),
  'emoji_sad_a.png': require('../../assets/emojis/emoji_sad_a.png'),
  'emoji_sad_b.png': require('../../assets/emojis/emoji_sad_b.png'),
  'emoji_sad_c.png': require('../../assets/emojis/emoji_sad_c.png'),
  'emoji_sad_d.png': require('../../assets/emojis/emoji_sad_d.png'),
  'emoji_scissors.png': require('../../assets/emojis/emoji_scissors.png'),
  'emoji_sigh_a.png': require('../../assets/emojis/emoji_sigh_a.png'),
  'emoji_sigh_b.png': require('../../assets/emojis/emoji_sigh_b.png'),
  'emoji_sigh_c.png': require('../../assets/emojis/emoji_sigh_c.png'),
  'emoji_sigh_d.png': require('../../assets/emojis/emoji_sigh_d.png'),
  'emoji_sing_a.png': require('../../assets/emojis/emoji_sing_a.png'),
  'emoji_sing_b.png': require('../../assets/emojis/emoji_sing_b.png'),
  'emoji_sing_c.png': require('../../assets/emojis/emoji_sing_c.png'),
  'emoji_sing_d.png': require('../../assets/emojis/emoji_sing_d.png'),
  'emoji_sneaky_a.png': require('../../assets/emojis/emoji_sneaky_a.png'),
  'emoji_sneaky_b.png': require('../../assets/emojis/emoji_sneaky_b.png'),
  'emoji_sneaky_c.png': require('../../assets/emojis/emoji_sneaky_c.png'),
  'emoji_sneaky_d.png': require('../../assets/emojis/emoji_sneaky_d.png'),
  'emoji_surprise_a.png': require('../../assets/emojis/emoji_surprise_a.png'),
  'emoji_surprise_b.png': require('../../assets/emojis/emoji_surprise_b.png'),
  'emoji_surprise_c.png': require('../../assets/emojis/emoji_surprise_c.png'),
  'emoji_surprise_d.png': require('../../assets/emojis/emoji_surprise_d.png'),
  'emoji_tete_a.png': require('../../assets/emojis/emoji_tete_a.png'),
  'emoji_tete_b.png': require('../../assets/emojis/emoji_tete_b.png'),
  'emoji_tete_c.png': require('../../assets/emojis/emoji_tete_c.png'),
  'emoji_tete_d.png': require('../../assets/emojis/emoji_tete_d.png'),
};

export function getEmojiSource(file: string): any {
  return emojiMap[file] || null;
}
